name: Invitation to the GitHub Community Organization
description: I would like to be part of ZeroOctave
title: "Please invite me to the GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: tech stack
    attributes:
      label: Your Tech Stack
      placeholder: html, css...
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What would you like to do in this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also follow us on Twitter [here](https://twitter.com/zero_octave)
       
